services:
  access-control:
    build:
      context: ./rpi
    container_name: access-control
    restart: unless-stopped
    network_mode: host
    environment:
      BOT_TOKEN: "${BOT_TOKEN}"
      ALLOWED_CHAT_ID: "${ALLOWED_CHAT_ID}"
      ACCESS_KEY: "${ACCESS_KEY}"
